pipeline:
  name: Amit Node App Pipeline
  identifier: amitnodeapp
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  codebase:
    connectorRef: gudul
    repoName: amit2k15/amit-node-app
    build:
      type: branch
      spec:
        branch: main
  properties:
    ci:
      codebase:
        connectorRef: nodeapp
        repoName: amit-node-app
        build: <+input>
  stages:
    - stage:
        name: Build Node App
        identifier: Build_Node_App
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  name: Install Dependencies
                  identifier: Install_Dependencies
                  type: Run
                  spec:
                    shell: Sh
                    command: npm install
              - step:
                  name: Run Tests
                  identifier: Run_Tests
                  type: Run
                  spec:
                    shell: Sh
                    command: npm test
              - step:
                  name: Build Project
                  identifier: Build_Project
                  type: Run
                  spec:
                    shell: Sh
                    command: npm run build
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - docker-delegate
