pipeline:
  name: Amit Node App Pipeline
  identifier: amitnodeapp
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build Node App
        identifier: Build_Node_App
        type: CI
        spec:
          execution:
            steps:
              - step:
                  name: Install Dependencies
                  identifier: Install_Dependencies
                  type: Run
                  spec:
                    shell: Sh
                    command: npm install
              - step:
                  name: Run Tests
                  identifier: Run_Tests
                  type: Run
                  spec:
                    shell: Sh
                    command: npm test
              - step:
                  name: Build Project
                  identifier: Build_Project
                  type: Run
                  spec:
                    shell: Sh
                    command: npm run build
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - docker-delegate
